#!/bin/bash
# deploy: sudo cp aws-vault-persist /usr/local/bin/
set -e

eval $(aws-vault export --format=export-env ${AWS_PROFILE})

TARGET_PROFILE=${AWS_PROFILE}-session

aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} --profile ${TARGET_PROFILE}
aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} --profile ${TARGET_PROFILE}
aws configure set aws_session_token ${AWS_SESSION_TOKEN} --profile ${TARGET_PROFILE}
aws configure set region us-west-2 --profile ${TARGET_PROFILE}
echo "Credentials for ${TARGET_PROFILE} refreshed"
